### ISSUE TITLE
Invites failing?

### ISSUE THREAD

**Issue by rabble** [fraction/ssb-cli#11]
I'm not sure if this is an ssb-cli issue or some underlying issue:

> /home/rabble$ ssb invite use scuttlebutt.de:8008:@yeh/GKxlfhlYXSdgU7CRLxm58GC42za3tDuC4NJld/k=.ed25519~iyaCpZ0co863K9aF+b7j8BnnHfwY65dGeX6Dh2nXs3c=
> TypeError: Param 0 must by of type object
>     at new ZE (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/zerr/index.js:11:42)
>     at Object.ZError [as Type] (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/zerr/index.js:13:14)
>     at validate (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/muxrpc-validation/index.js:161:22)
>     at Object.<anonymous> (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/muxrpc-validation/index.js:82:17)
>     at Object.hooked (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/hoox/index.js:10:15)
>     at Object.localCall (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/muxrpc/local-api.js:31:29)
>     at Object.<anonymous> (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/muxrpc/local-api.js:37:22)
>     at Object.request (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/muxrpc/stream.js:48:17)
>     at PacketStream._onrequest (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/packet-stream/index.js:161:17)
>     at PacketStream.write (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/packet-stream/index.js:134:41)

And a similar error with a different stacktrace 

> ~  ssb invite use scuttlebutt.de:8008:@yeh/GKxlfhlYXSdgU7CRLxm58GC42za3tDuC4NJld/k=.ed25519~iyaCpZ0co863K9aF+b7j8BnnHfwY65dGeX6Dh2nXs3c=          Mon Dec 21 17:40:22 2020
> Error [TypeError]: Param 0 must by of type object
>     at new ZE (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/zerr/index.js:11:42)
>     at Object.ZError [as Type] (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/zerr/index.js:13:14)
>     at validate (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/muxrpc-validation/index.js:161:22)
>     at Object.<anonymous> (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/muxrpc-validation/index.js:82:17)
>     at Object.hooked (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/hoox/index.js:10:15)
>     at Object.localCall (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/muxrpc/local-api.js:31:29)
>     at Object.<anonymous> (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/muxrpc/local-api.js:37:22)
>     at Object.request (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/muxrpc/stream.js:48:17)
>     at PacketStream._onrequest (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/packet-stream/index.js:161:17)
>     at PacketStream.write (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/packet-stream/index.js:134:41)

**Comment by christianbundy** [comment]
Can you try replacing `use` with `accept`? I think `use()` is a weird internal method, but if you're passing an SSB invite you want `ssb invite accept`.
