### ISSUE TITLE
ssb publish with no arguments throws error

### ISSUE THREAD

**Issue by timjrobinson** [fraction/ssb-cli#2]
Just cloned the repository (version 1.4.0) and tried `ssb publish` to discover what the parameters were for it and it threw an exception:

```
tim@TimThink:~/projects/ssb-cli$ ssb publish
(node:5279) UnhandledPromiseRejectionWarning: #<Object>
(node:5279) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5279) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

`ssb publish --help` works, but doesn't give instructions on the parameters required to publish.

**Comment by christianbundy** [comment]
Thanks for the bug report! I'll check this out and see what's going on. The ssb-db library doesn't actually provide any usage info for `publish()`, so that's something that will need to be fixed in that repo, but I can take care of the unhandled promise rejection.

**Comment by christianbundy** [comment]
Fixed in 1.4.2! Now this should output the actual error:

```console
$ ssb publish
Error: type must be a string3 <= type.length < 52, was:undefined
    at exports.isInvalidContent (/home/christianbundy/src/oasis/node_modules/ssb-validate/index.js:68:14)
    at exports.isInvalidShape (/home/christianbundy/src/oasis/node_modules/ssb-validate/index.js:109:10)
    at Object.exports.create (/home/christianbundy/src/oasis/node_modules/ssb-validate/index.js:272:13)
    at /home/christianbundy/src/oasis/node_modules/ssb-db/minimal.js:194:19
    at EventEmitter.append (/home/christianbundy/src/oasis/node_modules/ssb-db/minimal.js:162:18)
    at Object.add (/home/christianbundy/src/oasis/node_modules/ssb-db/create.js:103:10)
    at apply (/home/christianbundy/src/oasis/node_modules/muxrpc-validation/index.js:197:15)
    at Object.<anonymous> (/home/christianbundy/src/oasis/node_modules/muxrpc-validation/index.js:86:14)
    at Object.hooked (/home/christianbundy/src/oasis/node_modules/hoox/index.js:10:15)
    at Object.localCall (/home/christianbundy/src/oasis/node_modules/muxrpc/local-api.js:31:29)
```

Not super helpful, but I think the usage info / error text is probably something we'll want to fix in ssb-db.

**Comment by christianbundy** [comment]
Btw, this error should be something like "your message must have a type". Try:

```sh
ssb publish --type test --text "hello world"
```

**Comment by timjrobinson** [comment]
Such a quick fix! Thanks!
