### ISSUE TITLE
"ssb friends onEdge" crashes ssb-daemon

### ISSUE THREAD

**Issue by zicmama** [fraction/ssb-cli#7]
ssb friends onEdge
```
Error: unexpected hangup
    at Object.cb (/home/pi/.nvm/versions/node/v12.16.1/lib/node_modules/ssb-cli/node_modules/pull-box-stream/index.js:117:44)
    at drain (/home/pi/.nvm/versions/node/v12.16.1/lib/node_modules/ssb-cli/node_modules/pull-reader/index.js:46:23)
    at /home/pi/.nvm/versions/node/v12.16.1/lib/node_modules/ssb-cli/node_modules/pull-reader/index.js:63:18
    at /home/pi/.nvm/versions/node/v12.16.1/lib/node_modules/ssb-cli/node_modules/pull-reader/index.js:114:13
    at drain (/home/pi/.nvm/versions/node/v12.16.1/lib/node_modules/ssb-cli/node_modules/stream-to-pull-stream/index.js:126:18)
    at Socket.<anonymous> (/home/pi/.nvm/versions/node/v12.16.1/lib/node_modules/ssb-cli/node_modules/stream-to-pull-stream/index.js:143:5)
    at Socket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by christianbundy** [comment]
I don't think this is something we can fix. From the docs: https://github.com/ssbc/ssb-friends#onedge-fn--removelistener

> subscribe to changes in the graph. This can only be called locally by another in-process scuttlebot plugin.

These calls are being made over MuxRPC, not "another in-process scuttlebot plugin". I think this is a bug in the SSB-Friends plugin, unfortunately.
