### ISSUE TITLE
blobs meta

### ISSUE THREAD

**Issue by treasuretron** [fraction/ssb-cli#8]
```
ssb blobs meta

Oops! It looks like this method is advertised over muxrpc but not actually
available on the server. Let a developer know about this problem and someone
will fix it immediately.
```

What is ssb blobs meta supposed to do anyway? It's listed as a command from `ssb blobs --help`

(my real question is how to add a blob... I assumed it was something like`ssb blobs push "test2.jpg"` or `cat test2.jpg | ssb blobs push` but they both return,

```
+Error: invalid hash:null
    at Object.push (/usr/local/lib/node_modules/@fraction/oasis/node_modules/ssb-blobs/inject.js:343:19)
    at Object.hooked (/usr/local/lib/node_modules/@fraction/oasis/node_modules/hoox/index.js:10:15)
    at Object.localCall (/usr/local/lib/node_modules/@fraction/oasis/node_modules/muxrpc/local-api.js:31:29)
    at Object.<anonymous> (/usr/local/lib/node_modules/@fraction/oasis/node_modules/muxrpc/local-api.js:37:22)
    at Object.request (/usr/local/lib/node_modules/@fraction/oasis/node_modules/muxrpc/stream.js:48:17)
    at PacketStream._onrequest (/usr/local/lib/node_modules/@fraction/oasis/node_modules/packet-stream/index.js:161:17)
    at PacketStream.write (/usr/local/lib/node_modules/@fraction/oasis/node_modules/packet-stream/index.js:134:41)
    at /usr/local/lib/node_modules/@fraction/oasis/node_modules/muxrpc/pull-weird.js:56:15
    at /usr/local/lib/node_modules/@fraction/oasis/node_modules/pull-stream/sinks/drain.js:24:37
    at /usr/local/lib/node_modules/@fraction/oasis/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
```

Happens on both Oasis 2.15.0 and 2.16.0 after I upgraded to it.

EDIT:
ok found `/usr/local/lib/node_modules/@fraction/oasis/node_modules/ssb-blobs/README.md`
which doesn't quite explain it and links to `https://github.com/ssbc/secret-stack/blob/master/plugins.md` which doesn't exist. Sorry for the messy Issue! Just taking notes on what I'm finding....

thanks!!!

**Comment by christianbundy** [comment]
Hi!

I have no idea, I think that functionality comes from https://github.com/ssbc/ssb-blobs/ but I don't remember what it's for. Adding blobs is supposed to be `ssb blobs add < file.jpeg` I think, but it requires a 'sink' stream where we upload a file to the server. Turns out there's lots of additional programming complexity when you use streams for some things but not for others. Also, `ssb blobs add` doesn't actually even tell you the hash of the blob you just uploaded, so this is [hacked into ssb-server](https://github.com/ssbc/ssb-server/blob/bb11f7ce9092085556e2084fc26dcda8458c677b/bin.js#L129-L156) but not implemented in SSB-CLI. :/

After burning a bunch of hours trying to remain build better compatibility layers for the current back-end APIs I'm starting to think that maybe I should just write a new back-end. Sorry this isn't working correctly right now.
